import { StyleSheet, Platform } from 'react-native';
import { Spacing, BorderRadius, Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) => {
  // Web 端输入框通用样式
  const webInputStyle: any = Platform.OS === 'web' ? {
    outlineStyle: 'none',
  } : {};

  return StyleSheet.create({
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: Spacing.lg,
      paddingTop: Spacing['2xl'],
      paddingBottom: Spacing['5xl'],
    },
    header: {
      marginBottom: Spacing['2xl'],
    },
    subtitle: {
      marginTop: Spacing.sm,
    },
    section: {
      marginBottom: Spacing['2xl'],
    },
    sectionTitle: {
      marginBottom: Spacing.lg,
    },
    sectionTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      marginBottom: Spacing.lg,
    },
    typeGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.md,
    },
    typeCard: {
      width: '30%',
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.xl,
      padding: Spacing.lg,
      alignItems: 'center',
      borderWidth: 2,
      borderColor: 'transparent',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    typeCardSelected: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
      shadowOpacity: 0.15,
      elevation: 4,
    },
    typeIconContainer: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: theme.backgroundTertiary,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: Spacing.sm,
    },
    typeIconContainerSelected: {
      backgroundColor: 'rgba(255,255,255,0.2)',
    },
    typeLabel: {
      marginTop: Spacing.xs,
    },
    typeOtherRow: {
      marginTop: Spacing.md,
    },
    typeCardOther: {
      width: '100%',
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.xl,
      padding: Spacing.lg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: 'transparent',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
      gap: Spacing.md,
    },
    typeOtherIconContainer: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: theme.backgroundTertiary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    typeOtherIconContainerSelected: {
      backgroundColor: 'rgba(255,255,255,0.2)',
    },
    customTypeContainer: {
      marginTop: Spacing.xl,
      flexDirection: 'row',
      alignItems: 'center',
    },
    customTypeInput: {
      flex: 1,
      marginLeft: Spacing.md,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.md,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      fontSize: 16,
      color: theme.textPrimary,
      ...webInputStyle,
    },
    photosScroll: {
      marginBottom: Spacing.md,
    },
    photosScrollContent: {
      paddingTop: 12,
      paddingBottom: 4,
      paddingLeft: 4,
      paddingRight: 4,
    },
    photoItem: {
      width: 80,
      height: 80,
      borderRadius: BorderRadius.lg,
      overflow: 'visible',
      position: 'relative',
      marginRight: Spacing.md,
    },
    photoThumbnail: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
      borderRadius: BorderRadius.lg,
    },
    photoContainer: {
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.xl,
      overflow: 'hidden',
      borderWidth: 2,
      borderColor: theme.border,
      borderStyle: 'dashed',
    },
    photoPlaceholder: {
      height: 150,
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.md,
    },
    photoPlaceholderText: {
      marginTop: Spacing.sm,
    },
    photoRequirement: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      marginTop: Spacing.md,
      paddingHorizontal: Spacing.md,
    },
    photoRequirementText: {
      textAlign: 'center',
    },
    photoPreviewWrapper: {
      position: 'relative',
    },
    photoPreview: {
      width: '100%',
      height: 200,
      resizeMode: 'cover',
    },
    removePhotoButton: {
      position: 'absolute',
      top: -8,
      right: -8,
      backgroundColor: 'rgba(255,255,255,0.95)',
      borderRadius: 12,
      padding: 2,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 2,
    },
    uploadingOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(255,255,255,0.8)',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BorderRadius.xl,
    },
    durationGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.md,
    },
    durationCard: {
      width: '30%',
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.lg,
      padding: Spacing.lg,
      alignItems: 'center',
      borderWidth: 2,
      borderColor: 'transparent',
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    durationCardSelected: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
      shadowOpacity: 0.15,
      elevation: 4,
    },
    customDurationContainer: {
      marginTop: Spacing.xl,
      flexDirection: 'row',
      alignItems: 'center',
    },
    customDurationInput: {
      flex: 1,
      marginLeft: Spacing.md,
      backgroundColor: theme.backgroundTertiary,
      borderRadius: BorderRadius.md,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.md,
      fontSize: 16,
      color: theme.textPrimary,
      ...webInputStyle,
    },
    saveButton: {
      backgroundColor: theme.primary,
      borderRadius: BorderRadius.xl,
      paddingVertical: Spacing.xl,
      alignItems: 'center',
      marginTop: Spacing.lg,
      shadowColor: theme.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 4,
    },
    saveButtonDisabled: {
      opacity: 0.6,
    },
    todayRecordCard: {
      backgroundColor: theme.backgroundDefault,
      borderRadius: BorderRadius.xl,
      padding: Spacing.lg,
      marginBottom: Spacing.xl,
      borderLeftWidth: 4,
      borderLeftColor: theme.success,
    },
    todayRecordHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: Spacing.sm,
    },
    todayRecordTitle: {
      marginLeft: Spacing.sm,
    },
    todayRecordTip: {
      marginTop: Spacing.sm,
    },
  });
};
